### ISSUE TITLE
Issue in handling boolean value

### ISSUE THREAD

**Issue by ckdanny** [seperman/redisworks#11]
When I use redisworks to set the True/False value, it can successfully set. 
But when read it, the evaluation result will be always True.

**Comment by seperman** [comment]
Hi @ckdanny 
Thanks for reporting this. I will check.

**Comment by acidbotmaker** [comment]
This is happening cause in `get_obj` method, `value = actual_type(value)` is called i.e., which evaluates to `value = bool("False")` which is always going to be true.

**Comment by seperman** [comment]
Redisworks 0.4.0 is released and this issue is resolved.
