### ISSUE TITLE
Dynamically changing root key name

### ISSUE THREAD

**Issue by eevleevs** [seperman/redisworks#13]
Took me a while to understand how to set the root key to a dynamic string.
Might be worth to note it on the instructions:

```
>>> class Post(Root):
...     pass
>>> post=Post()
```
can also be done as

`>>> post = type('Post', (Root,), {})()`

**Comment by seperman** [comment]
Cool. I will add it to the docs. Thanks.

**Comment by acidbotmaker** [comment]
Maybe we can pass the namespace in Root's constructor to set keys dynamically like the following:

```
>>> from redisworks import Root
>>> root = Root(namespace="post")
>>> root.item1 = "something"  # saves to Redis
```

**Comment by seperman** [comment]
@acidbotmaker Yeah that is a great idea. Much simpler than `post = type('Post', (Root,), {})()`

**Comment by seperman** [comment]
Thanks to @acidbotmaker for the PR. I am merging it.

**Comment by seperman** [comment]
Redisworks 0.4.0 is released and this issue is resolved.
