### ISSUE TITLE
Password not passed to pyredis

### ISSUE THREAD

**Issue by FinBauer** [seperman/redisworks#15]
Initiating Root with password argument seems to fail. I think this is because the password is not passed on to pyredis on line 61 of redisworks.py. It can easily be circumvented by instead passing the pyredis connection object via the conn argument, but should probably be fixed. Thank you for this really helpful module!

**Comment by seperman** [comment]
Hi @FinBauer 
Thanks for reporting this. Sorry it took me a year to look at this ticket. I'm releasing a cut soon.

**Comment by seperman** [comment]
Redisworks 0.4.0 is released and this issue is resolved.
