### ISSUE TITLE
ending underscores disappear after reconnection

### ISSUE THREAD

**Issue by emieza** [seperman/redisworks#5]
This example is quite clear. Although the content in the Redis DB is still "aaa_", accessing after redisworks reconnections returns only "aaa" without the ending underscore.

```python
>>> r["prova"] = "aaa_"
>>> 
>>> 
>>> print(r["prova"])
aaa_
>>> 
(envTg) enric@ubuntu:~/apps/bots$ 
(envTg) enric@ubuntu:~/apps/bots$ python
Python 3.5.2 (default, Nov 17 2016, 17:05:23) 
[GCC 5.4.0 20160609] on linux
Type "help", "copyright", "credits" or "license" for more information.
>>> import redisworks
>>> r = redisworks.Root()
>>> r["prova"]
<Lazy object: root.prova>
>>> print(r["prova"])
aaa
>>> 
```

In the Redis console:
```
127.0.0.1:6379> get "root.prova"
"!__str|==|str|==|aaa_"
```

Do you think you can take a look at some stage?
Thanks a lot, your work is good and really useful :)

Cheers!

**Comment by seperman** [comment]
Hi @emieza 
Sorry I have not got back to you. Have been super busy recently. I will try to fix it when I can. Thanks    for your comments!

**Comment by acidbotmaker** [comment]
Not only ending underscores, if the underscores are passed in start of the string, they'll be replaced too.
From [python docs](https://docs.python.org/3/library/stdtypes.html#str.strip) strip method takes char array and replaces each character in the string with leading and ending, pattern (or order) doesn't matter.
