### ISSUE TITLE
setting ttl

### ISSUE THREAD

**Issue by jinyus** [seperman/redisworks#9]
Is it possible to specify a ttl when saving to redis?

**Comment by seperman** [comment]
@jinyus Currently it doesn't have a method for this purpose. But I'm imaging maybe building something like
```
ttl = TTL(20)
root.x.y.z = ('value', ttl)
```

What do you think?

**Comment by eevleevs** [comment]
I would like `root.x.y.z = ('value', ttl=20)`

**Comment by seperman** [comment]
@acidbotmaker Yeah maybe we can have a special object dedicated to it so it can differentiate between it being tuple and that object. Like:
`root.x.y.z = WithTTL('value', ttl=20)`

**Comment by seperman** [comment]
Redisworks 0.4.0 is released and this issue is resolved.
https://github.com/seperman/redisworks/#passing-ttl-to-the-keys

**Comment by acidbotmaker** [comment]
I just noticed this change.
Thanks @seperman I will take a look at it.
